# Documentation: https://github.com/codecov/support/wiki/codecov.yml

codecov:
  ci:
    - "circleci.com"
  notify:
    after_n_builds: 1  # send notifications after the first upload
  bot: dlang-bot

coverage:
  precision: 3
  round: down
  range: "80...100"

  status:

    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false

comment: false
